Change LookandFeel    try {         UIManager.setLookAndFeel(      UIManager.getCrossPlatformLookAndFeelClassName());     } catch (Exception e) { }
To see if solve the problem
Invocation of this Java Application has caused an InvocationTargetException. This application will now exit. (LAX)


Stack Trace:
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at sun.awt.X11.XFramePeer.setIconImage(Unknown Source)
        at sun.awt.X11.XFramePeer.postInit(Unknown Source)
        at sun.awt.X11.XBaseWindow.init(Unknown Source)